export const DELETE_NOTE = 'DELETE_NOTE';
export const ADD_NOTE = 'ADD_NOTE';
export const CHANGE_INPUT = 'CHANGE_INPUT';
export const CLEAR_FORM = 'CLEAR_FORM';
export const LOAD_TYPES = 'LOAD_TYPES';
export const LOAD_TYPES_REQUEST = 'LOAD_TYPES_REQUEST';
export const LOAD_TYPES_SUCCESS = 'LOAD_TYPES_SUCCESS';
export const LOAD_TYPES_ERROR = 'LOAD_TYPES_ERROR';
